### ISSUE TITLE
Improve the teaser video display

### ISSUE THREAD

**Issue by chiantific** [chiantific/Roseville#30]

**Comment by dunatotatos** [comment]
Fixed in commit 33b45afd5ebbcefe2175ba7f497dd87992a83453
Cherry-pick to booking_temp coming soon

**Comment by dunatotatos** [comment]
Cherry-picked in commit 802cca3d69ab298d864c3c57af7aa55f7fd00ba0

**Comment by dunatotatos** [comment]
Je n'ai fait qu'une seule modification : le plein écran est maintenant possible.
Je ferme le ticket. Si la modification ne suffit pas, rouvre-le en décrivant ce qu'il manque.
