### ISSUE TITLE
google font should be served over https

### ISSUE THREAD

**Issue by chiantific** [chiantific/Roseville#46]

**Comment by dunatotatos** [comment]
Fixed in commit 956726720e9851a1c5a8641fe2ac2a0e5cbf0e1f

**Comment by dunatotatos** [comment]
To cherry-pick in booking_temp

**Comment by dunatotatos** [comment]
Fixed in commit b06135e942748f387cb3cb26815dda8e2dc4b3b9 on booking_temp
