### ISSUE TITLE
Teaser is not loading

### ISSUE THREAD

**Issue by chiantific** [chiantific/Roseville#52]
The associated message in the console
jquery.prettyPhoto.js:7 Mixed Content: The page at 'https://escape.roseville.ch/#prettyPhoto/0/' was loaded over HTTPS, but requested an insecure resource 'http://www.youtube.com/embed/GyssJMtZRaM?rel=1&autoplay=1'. This request has been blocked; the content must be served over HTTPS.

**Comment by dunatotatos** [comment]
Bug introduced here : 4abd9b73830d23083003860dd543f66944f9453d

**Comment by dunatotatos** [comment]
Fixed in commit b0a3533de19752e432b9b7efec1dd21ea10889b0

**Comment by chiantific** [comment]
fix in commit fc8d7e8c91e7a19da8bf111aa10d3d80ddb57487
to do cherry pick

**Comment by dunatotatos** [comment]
Cherry-pick is done 06cc10301c52e4a7a40aa2304718e3e20cea28a3
