### ISSUE TITLE
In backend modify description of language status 

### ISSUE THREAD

**Issue by chiantific** [chiantific/Roseville#59]

**Comment by dunatotatos** [comment]
Is it fixed?
The description now is "French" or "English". Description fits the language of the backend.

Can you confirm?

**Comment by chiantific** [comment]
It is not fixed but not critical either. 
Issue was raised because the way that the language menu displays in the backend is not consistent with the front end. Should display "EN" when backend/site is shown in french and "FR" when backend/site is in english

**Comment by dunatotatos** [comment]
Oh! You talk about the language switch button? I thought this issue was about the description of an appointment.

**Comment by dunatotatos** [comment]
Booking is managed by Planyo.
