### ISSUE TITLE
In backend modify description of payment status

### ISSUE THREAD

**Issue by chiantific** [chiantific/Roseville#60]

**Comment by dunatotatos** [comment]
La version actuelle est bonne, ou il faut faire mieux ? Comment ?

**Comment by dunatotatos** [comment]
Can you confirm?

**Comment by chiantific** [comment]
The current version is okay with the yes or no instead of 0 or 1.

However

We need to add one more payment status to discriminate between not paid/invalid booking originating from the front end, and not paid when people call us/send us a msg to book. In the latter case, it agreed that people will pay in cash after the game (but we need a way to remember to ask).

Different colors might take care of that. Red not paid/invalid booking, blue not paid/valid booking, green paid booking

**Comment by dunatotatos** [comment]
New task created as Issue #76
