### ISSUE TITLE
The field "note" is missing in the reservation detail in the backed

### ISSUE THREAD

**Issue by chiantific** [chiantific/Roseville#66]
Notes are send via email upon successful reservation and payment

**Comment by dunatotatos** [comment]
Really needed?
Note can be a long message and can destroy the format of the popover. While the note field is already sent by mail and is available when editing an appointment, I'm not sure we need to see it in this little popover.

And what about hiding the payment status as well, as this information is already seen by the color?
And the Beginnning and End of the appointment?

**Comment by chiantific** [comment]
notes are extremely useful.
We write special need from the customer (apéro before, special chair, anniversary, champagne, flower, ....). We also write if people will pay in cash (I guess color can take care of that).
We can also add in there the name of the coach.

**Comment by chiantific** [comment]
There are 2 informations fields. One in the booking details, in which customers can add a notes.
The second one can be only populated from the backend. It is associated with the "your details". 
We could use one of them to write short notes about the booking. It would be nice if it appears in the popover. Especially if one search for an info. It is a pain to open every reservation

**Comment by chiantific** [comment]
Regarding the second notes field, the one associated with the "Your details" section, if you put a line break when you write the message, you get an error message when you try to save the appointment.
"Unexpected Issues
The operation could not complete due to unexpected issues.

Details
Not all required fields are provided : "

**Comment by dunatotatos** [comment]
Fixed in cb5cd36
