### ISSUE TITLE
mishandle of available dates when superposition of unavailable time and reservation in the backend

### ISSUE THREAD

**Issue by chiantific** [chiantific/Roseville#67]
if you create new bookings or unavailables (for when we do not have a coach, for examples) manually from the backend, it is possible to make mistakes when picking the time which results sometimes in overlaps. In theses cases, time spans covered by the overlaping booking/unavailable are still offered on the front end. Not good because we might end up with someone booking precisely at that time. Look on March 26/27 at 13:30 for examples

**Comment by dunatotatos** [comment]
Haha, on peut ajouter des smileys !

**Comment by dunatotatos** [comment]
Je n'arrive pas à reproduire de comportement étrange. Peux-tu tester et donner des détails ?

**Comment by dunatotatos** [comment]
Can you confirm?

**Comment by dunatotatos** [comment]
Can you confirm?

**Comment by chiantific** [comment]
Salut,

 

Oui, Ça fonctionne correctement maintenant, c'est-à-dire que la plage horaire du rendez-vous qui en chevauche un autre n'apparait plus comme disponible dans le calendrier.

 

Merci

 

A+

Hubert

**Comment by dunatotatos** [comment]
Booking is managed by Planyo.
