### ISSUE TITLE
limit the number of participants independently in each room

### ISSUE THREAD

**Issue by chiantific** [chiantific/Roseville#70]
max number of participant for the room chocolat is 6
max number of participants for the room in vino veritas is 5

It works ok now

**Comment by dunatotatos** [comment]
Attach number of participants to ea_room. Need #41

**Comment by dunatotatos** [comment]
Added javascript (client-side) part in commit b76dde4759f4a8b686c2eb84550554f2bedaaf2d

**Comment by dunatotatos** [comment]
Do not close this one yet, as I want to move the settings to the backend instead of having an hard limit in the client side.

**Comment by dunatotatos** [comment]
Booking is managed by Planyo.
