### ISSUE TITLE
No confirmation email is sent to info at roseville dot ch for IVV bookings

### ISSUE THREAD

**Issue by chiantific** [chiantific/Roseville#72]

**Comment by dunatotatos** [comment]
Can you check the address configured for the room?
I see no error message in the log files, and it works as expected in test.

**Comment by chiantific** [comment]
The address was set to chiantific at gmail dot com. Mails do actually accumulate there, so it works. The problem lies in the fact that the IVV's mailing address cannot be set to info at roseville dot ch, which is already set for chocolat. If I try I get an error message. Temporary solved the problem by creating a new email address at OVH and redirecting messages to info. Would be better to send it directly.

**Comment by dunatotatos** [comment]
This can be fixed by allowing the same e-mail address for different rooms. I won't fix that, as it will be correctly used when switching the current room to the previously un-used "service". Modifying that will allow us to independently manage the coach, and fine-tune the notifications.
